<?php namespace App\Database\Seeds;

class TableManagementSeeder extends \CodeIgniter\Database\Seeder
{
        public $table = 'permissions';

        public function run()
        {
                $data = [
                  [
                    'function_name' => 'list of course',
                    'function_description' => 'list of course',
                    'slugs' => 'list-course',
                    'name_on_class' => 'index',
                    'page_title' => 'list of course',
                    'module_id' => '3',
                    'link_icon' => '<i class="far fa-circle"></i>',
                    'order' => '1',
                    'table_name' => 'course',
                    'func_action' => 'link',
                    'func_type' => 1,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'create course',
                    'function_description' => 'create course',
                    'slugs' => 'add-course',
                    'name_on_class' => 'add_course',
                    'page_title' => 'creating a course',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '2',
                    'table_name' => 'course',
                    'func_action' => 'add',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],

                  [
                    'function_name' => 'show course details',
                    'function_description' => 'show course details',
                    'slugs' => 'show-course',
                    'name_on_class' => 'show_course',
                    'page_title' => 'course details',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '3',
                    'table_name' => 'course',
                    'func_action' => 'show',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'edit course',
                    'function_description' => 'edit course',
                    'slugs' => 'edit-course',
                    'name_on_class' => 'edit_course',
                    'page_title' => 'edit course',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '4',
                    'table_name' => 'course',
                    'func_action' => 'edit',
                    'func_type' => 3,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'delete course',
                    'function_description' => 'delete course',
                    'slugs' => 'delete-course',
                    'name_on_class' => 'delete_course',
                    'page_title' => 'delete course',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '5',
                    'table_name' => 'course',
                    'func_action' => 'delete',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  //Schoolyear Seeder
                  [
                    'function_name' => 'list of schyear',
                    'function_description' => 'list of schyear',
                    'slugs' => 'list-schyear',
                    'name_on_class' => 'index',
                    'page_title' => 'list of schyear',
                    'module_id' => '3',
                    'link_icon' => '<i class="far fa-circle"></i>',
                    'order' => '6',
                    'table_name' => 'schyear',
                    'func_action' => 'link',
                    'func_type' => 1,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'creating schyear',
                    'function_description' => 'creating schyear',
                    'slugs' => 'add-schyear',
                    'name_on_class' => 'add_schyear',
                    'page_title' => 'creating a schyear',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '7',
                    'table_name' => 'schyear',
                    'func_action' => 'add',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'show schyear details',
                    'function_description' => 'show schyear details',
                    'slugs' => 'show-schyear',
                    'name_on_class' => 'show_schyear',
                    'page_title' => 'schyear details',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '8',
                    'table_name' => 'schyear',
                    'func_action' => 'show',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'edit schyear',
                    'function_description' => 'edit schyear',
                    'slugs' => 'edit-schyear',
                    'name_on_class' => 'edit_schyear',
                    'page_title' => 'edit schyear',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '9',
                    'table_name' => 'schyear',
                    'func_action' => 'edit',
                    'func_type' => 3,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'delete schyear',
                    'function_description' => 'delete schyear',
                    'slugs' => 'delete-schyear',
                    'name_on_class' => 'delete_schyear',
                    'page_title' => 'delete schyear',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '10',
                    'table_name' => 'schyear',
                    'func_action' => 'delete',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],

                  //Section Seeder
                  // [
                  //   'function_name' => 'list of section',
                  //   'function_description' => 'list of section',
                  //   'slugs' => 'list-section',
                  //   'name_on_class' => 'index',
                  //   'page_title' => 'list of section',
                  //   'module_id' => '3',
                  //   'link_icon' => '<i class="fas fa-users"></i>',
                  //   'order' => '211',
                  //   'table_name' => 'section',
                  //   'func_action' => 'link',
                  //   'func_type' => 1,
                  //   'allowed_roles' => "[1,2]",
                  //   'status' => 'a',
                  //   'created_at' => date('Y-m-d H:i:s')
                  // ],
                  // [
                  //   'function_name' => 'creating section',
                  //   'function_description' => 'creating section',
                  //   'slugs' => 'add-section',
                  //   'name_on_class' => 'add_section',
                  //   'page_title' => 'creating a section',
                  //   'module_id' => '3',
                  //   'link_icon' => '',
                  //   'order' => '212',
                  //   'table_name' => 'section',
                  //   'func_action' => 'add',
                  //   'func_type' => 3,
                  //   'allowed_roles' => "[1]",
                  //   'status' => 'a',
                  //   'created_at' => date('Y-m-d H:i:s')
                  // ],
                  // [
                  //   'function_name' => 'show section details',
                  //   'function_description' => 'show section details',
                  //   'slugs' => 'show-section',
                  //   'name_on_class' => 'show_section',
                  //   'page_title' => 'section details',
                  //   'module_id' => '3',
                  //   'link_icon' => '',
                  //   'order' => '213',
                  //   'table_name' => 'section',
                  //   'func_action' => 'show',
                  //   'func_type' => 3,
                  //   'allowed_roles' => "[1]",
                  //   'status' => 'a',
                  //   'created_at' => date('Y-m-d H:i:s')
                  // ],
                  // [
                  //   'function_name' => 'edit section',
                  //   'function_description' => 'edit section',
                  //   'slugs' => 'edit-section',
                  //   'name_on_class' => 'edit_section',
                  //   'page_title' => 'edit section',
                  //   'module_id' => '3',
                  //   'link_icon' => '',
                  //   'order' => '214',
                  //   'table_name' => 'section',
                  //   'func_action' => 'edit',
                  //   'func_type' => 3,
                  //   'allowed_roles' => "[1,2]",
                  //   'status' => 'a',
                  //   'created_at' => date('Y-m-d H:i:s')
                  // ],
                  // [
                  //   'function_name' => 'delete section',
                  //   'function_description' => 'delete section',
                  //   'slugs' => 'delete-section',
                  //   'name_on_class' => 'delete_section',
                  //   'page_title' => 'delete section',
                  //   'module_id' => '3',
                  //   'link_icon' => '',
                  //   'order' => '215',
                  //   'table_name' => 'section',
                  //   'func_action' => 'delete',
                  //   'func_type' => 3,
                  //   'allowed_roles' => "[1]",
                  //   'status' => 'a',
                  //   'created_at' => date('Y-m-d H:i:s')
                  // ],

                  // //Subject Seeder
                  [
                    'function_name' => 'list of subject',
                    'function_description' => 'list of subject',
                    'slugs' => 'list-subject',
                    'name_on_class' => 'index',
                    'page_title' => 'list of subject',
                    'module_id' => '3',
                    'link_icon' => '<i class="far fa-circle"></i>',
                    'order' => '11',
                    'table_name' => 'subject',
                    'func_action' => 'link',
                    'func_type' => 1,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'creating subject',
                    'function_description' => 'creating subject',
                    'slugs' => 'add-subject',
                    'name_on_class' => 'add_subject',
                    'page_title' => 'creating a subject',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '12',
                    'table_name' => 'subject',
                    'func_action' => 'add',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'show subject details',
                    'function_description' => 'show subject details',
                    'slugs' => 'show-subject',
                    'name_on_class' => 'show_subject',
                    'page_title' => 'subject details',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '13',
                    'table_name' => 'subject',
                    'func_action' => 'show',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'edit subject',
                    'function_description' => 'edit subject',
                    'slugs' => 'edit-subject',
                    'name_on_class' => 'edit_subject',
                    'page_title' => 'edit subject',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '14',
                    'table_name' => 'subject',
                    'func_action' => 'edit',
                    'func_type' => 3,
                    'allowed_roles' => "[1,2]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],
                  [
                    'function_name' => 'delete subject',
                    'function_description' => 'delete subject',
                    'slugs' => 'delete-subject',
                    'name_on_class' => 'delete_subject',
                    'page_title' => 'delete subject',
                    'module_id' => '3',
                    'link_icon' => '',
                    'order' => '15',
                    'table_name' => 'subject',
                    'func_action' => 'delete',
                    'func_type' => 3,
                    'allowed_roles' => "[1]",
                    'status' => 'a',
                    'created_at' => date('Y-m-d H:i:s')
                  ],

                ];
                $db      = \Config\Database::connect();
                $builder = $db->table($this->table);
                $builder->insertBatch($data);
        }
}
